### ISSUE TITLE
[issue] Cannot enter Short IP's or Long IP's

### ISSUE THREAD

**Issue by mon5termatt** [bigtreetech/K-Touch#10]
The Ktouch does not allow Short IP addresses 

Examples 

❌10.0.0.224
❌10.0.0.10
(too short) 
✔010.0.0.224

❌192.168.123.123
(too many)

**Comment by mon5termatt** [comment]
mentioned in #1 but that also has other issues in that issue. Making this one for ease of tracking.

**Comment by PoohWoah** [comment]
Good points. Thanks for taking the time to log these issues.
We will get this fixed up in the next FW release. We never caught it during testing because it seems that all of our testers had IP addresses that met the minimum length requirement.

**Comment by mon5termatt** [comment]
Some simple regex would be a lot better.

https://stackoverflow.com/questions/5284147/validating-ipv4-addresses-with-regexp

**Comment by BTTJUSTIN** [comment]
This bug was fixed in FW version V1.0.1
