### ISSUE TITLE
[ISSUE] Command queue jumps to the new printer

### ISSUE THREAD

**Issue by Fragmon** [bigtreetech/K-Touch#11]
In addition to this [issue](https://github.com/bigtreetech/K-Touch/issues/4), there is also a problem if there is likely to be a command queue. 

As an example to trigger the error: If you press the Home button 5 times and change the printer, for example, the remaining Homes are executed on the new printer. The same applies to the emergency shutdown.

**Comment by Rowan2233** [comment]
Hey bro, sorry for bring this experience for you, and really thank you for this feedback, we will try to fix this in next version.

**Comment by BTTJUSTIN** [comment]
This bug was fixed in FW version V1.0.1
