### ISSUE TITLE
Add a button to disable headbed and hottend (Cooldown)

### ISSUE THREAD

**Issue by Spolfox** [bigtreetech/K-Touch#15]
Add a button to cooldown (disable) headbed and hottend. There is only manual or automatic heating profiles to choose from, but there is no cooling.
You need to go to the extruder and write 0, then go to the hot table and write 0.

**Comment by Spolfox** [comment]
@bigtreetech

@K-touch

**Comment by yellowicz** [comment]
I just wanted to add the same request. Please add a Cooldown button.

**Comment by Spolfox** [comment]
Yes, I wrote about it, there is not enough of such an opportunity

**Comment by bigtreetech** [comment]
Coming in 1.0.1

**Comment by BTTJUSTIN** [comment]
This bug was fixed in FW version V1.0.1
