### ISSUE TITLE
[Feature Request] Macro & Console

### ISSUE THREAD

**Issue by exiom-xyz** [bigtreetech/K-Touch#2]
As per title, I would like to be able to trigger Macros via the K-Touch as well as the ability to view the Klipper Console

**Comment by RH3D** [comment]
+1 I'd like that too but just to add - in the K-Touch livestream it was already said that both will be a future update, so I believe BTT is/will be working on it.

**Comment by bombsquad85** [comment]
yes! came here to post this!

**Comment by BTTJUSTIN** [comment]
This feature was implemented in FW version V1.1.0
