### ISSUE TITLE
Creality K1 c and K1 max and K touch

### ISSUE THREAD

**Issue by Gismo6** [bigtreetech/K-Touch#23]
Have Creality K1 c and K1 max. The K touch cannot find these printers. IP address does not work because my IP address is longer 15 numbers, I can only enter 14.

**Comment by bistory** [comment]
Did you root your K1's and installed the a more recent version of Moonraker ?

**Comment by Gismo6** [comment]
no

**Comment by PoohWoah** [comment]
Okay, thank you for your question. The IP input issue will be fixed in the next version. Please refer to the details #1

**Comment by bistory** [comment]
> no

You have to, even when the ip issue will be fixer.

**Comment by Andy3dprinter** [comment]
> Have Creality K1 c and K1 max. The K touch cannot find these printers. IP address does not work because my IP address is longer 15 numbers, I can only enter 14.

I am running mine on a K1 however the others are correct. I rooted mine a long time ago and am using the script from Guilouz and it's been great. I rooted and installed full Klipper on the second day I bought it. It is worth it and you will get to learn and understand Klipper and things like Mainsail or Fluidd. :)

**Comment by BTTJUSTIN** [comment]
This bug was fixed in FW version V1.0.1
