### ISSUE TITLE
K-Touch cannot bind with pandaPWR

### ISSUE THREAD

**Issue by Learoy1** [bigtreetech/K-Touch#37]
Panda touch can bind with and control pandaPWR but K-Touch cannot bind with pandaPWR. 
PandaPWR should be perfect to constantly power a pi through the USB but shut off power to the printer.

**Comment by Rowan2233** [comment]
Hey bro, thank you for telling this, we will supported Panda PWR in K touch v1.1.0 soon ; )

**Comment by Rowan2233** [comment]
Hey bro, we are doing this feature function beta testing, would you like to join us?  I could open  access to you that repo latter.

**Comment by BTTJUSTIN** [comment]
This feature was implemented in FW version V1.1.0
