### ISSUE TITLE
[Issue] Emergency stop has major delay

### ISSUE THREAD

**Issue by Rappetor** [bigtreetech/K-Touch#4]
I hit the emergency stop on the K-Touch after starting something (think QGL) and it took a long time before it was executed. Expected behaviour when pressing this button (like on the printer or in the mainsail interface) is an immediate shutdown.

**Comment by PoohWoah** [comment]
Good points. Thank you for your question. We have never found this issue during our testing process, and we will fix it later. Thank you.

**Comment by bigtreetech** [comment]
> I hit the emergency stop on the K-Touch after starting something (think QGL) and it took a long time before it was executed. Expected behaviour when pressing this button (like on the printer or in the mainsail interface) is an immediate shutdown.

Are you sure that you pressed OK on the k-touch? We have tried many times and cannot replicate this. Are you able to replicate and film it?
