### ISSUE TITLE
[Feature Request] Customizable printer name

### ISSUE THREAD

**Issue by dongxunz** [bigtreetech/K-Touch#42]
Using the same hardware host computer, the connected 3D printers have the same name. Although their IP addresses are different, they cannot be quickly distinguished, so we hope to add the function of changing the name.

**Comment by BTTJUSTIN** [comment]
Thanks for making this suggestion. We will discuss it internally and let you know if it will be scheduled for a future firmware release.

**Comment by Rowan2233** [comment]
Hey bro, K-touch can rename the printer name. Please to hold the press the printer name at the printer page, and you will get a pop-up window to rename it.
