### ISSUE TITLE
[ISSUE] Large Thumbnails Makes UI Glitch / Scroll / Unresponsive.

### ISSUE THREAD

**Issue by mon5termatt** [bigtreetech/K-Touch#9]
https://youtu.be/QYWDmYZsOlE

**Comment by mon5termatt** [comment]
Thumbnails seem to cover the stats of the files. After a minute or so, the screen decides to scroll randomly and makes the UI unresponsive.

**Comment by PoohWoah** [comment]
Hello, thank you for raising the question. It is best to maintain a file thumbnail resolution of around 100x100 when reading on K-Touch. In the next version, K-Touch will adaptively adjust the size of the image based on the thumbnail resolution (provided that the resolution is below 100x100). This way, you can view higher definition thumbnails.

**Comment by PoohWoah** [comment]
Hello, thank you for raising the question. Please maintain the file thumbnail resolution for reading on K-Touch at around 100x100. If the file thumbnail resolution is too high, it will cause K-Touch resources to run out. So, in the current version, please set the thumbnail to around 100x100 when slicing to maintain K-Touch's normal reading of file thumbnails. In the next version of K-Touch, the image will be resized adaptively based on the resolution of the thumbnail. This way, you can view higher definition thumbnails.

**Comment by PoohWoah** [comment]
Hello, thank you for raising the question. Please maintain the file thumbnail resolution for reading on K-Touch at around 32x32. Currently, K-Touch scales based on this size, so if the file thumbnail resolution is too high, it will cause K-Touch to exhaust its resources and exceed its display range. So, in the current version, please set the thumbnail to around 32x32 when slicing to maintain K-Touch's normal reading of file thumbnails. In the next version of K-Touch, the image will be resized adaptively based on the resolution of the thumbnail. This way, you can view higher definition and more consistent sized thumbnails.

**Comment by mon5termatt** [comment]
32x32??? What are you going to even be able to make out at 32x32. That's not a thumbnail that's pixel art....

**Comment by PoohWoah** [comment]
> 32x32???你甚至能在 32x32 上看出什么。那不是像素艺术的缩略图......它是蚂蚁的缩略图！

More high-definition thumbnails will be displayed in the future, as defined in the current version. For the current 32x32 resolution thumbnail, we will enlarge it for you to view, but what you actually see is not 32x32.

**Comment by PoohWoah** [comment]
> 32x32???你甚至能在 32x32 上看出什么。那不是像素艺术的缩略图......它是蚂蚁的缩略图！

For the current 32x32 resolution thumbnail, we will enlarge it for you to view, but what you actually see is not 32x32. You can actually check it out.

**Comment by PoohWoah** [comment]
> 32x32???你甚至能在 32x32 上看出什么。那不是像素艺术的缩略图......它是蚂蚁的缩略图！

我们会使用别的方法让缩略图变大，这样做的目的只是为之后K-Touch能够读取到更多的缩略图而作的准备。比如我现在读取到的就是设置好分辨率的图片
![32x32](https://github.com/user-attachments/assets/06e7932e-8139-40a1-bd83-71df954d5b53)
可以看到它已经放大了，可以让我们清晰的看到。

**Comment by PoohWoah** [comment]
> 32x32??? What are you going to even be able to make out at 32x32. That's not a thumbnail that's pixel art.... Its a thumbnail for ants!

We will use other methods to make the thumbnail larger, but the purpose of doing so now is only to prepare for K-Touch to be able to read more thumbnails in the future. For example, what I am currently reading is an image with a set resolution.
![32x32](https://github.com/user-attachments/assets/faa0ab69-ae5f-41ac-b42b-495616ee2b02)
可以看到它已经放大了，可以让我们清晰的看到。

**Comment by PoohWoah** [comment]
Hello. Also, can you provide me with a GCode file?

**Comment by exiom-xyz** [comment]
> 32x32??? What are you going to even be able to make out at 32x32. That's not a thumbnail that's pixel art.... Its a thumbnail for ants!

if i recall correctly... the K-Touch/PandaTouch is based on the ESP32 so you need to keep in mind of it's performance capabilities... it is not like KlipperScreen where it runs off your raspberry pi or other SBC... for that you need something like the BTT Pad 7

**Comment by mon5termatt** [comment]
i understand that its running on a smaller cpu (heck i use esp32 boards all the time). And it doesn't bother me all that much, but the text not being on top of the thumbnail should be an important bug.

**Comment by mon5termatt** [comment]
or allow fewer items on screen with larger thumbnails,

**Comment by PoohWoah** [comment]
> 或者允许屏幕上使用较大的缩略图减少项目，

Yes, the next version will become an adaptive thumbnail. Currently, we only capture the 32X32 thumbnail that it defaults to transmitting to us. Our testers have not encountered the situation you mentioned. Can you provide me with a gcode file and we will check if there are any other issues.

**Comment by mon5termatt** [comment]
i cannot provide the same file as it has copyright to it, and i cannot share it, however i will provide a benchy using my settings.

**Comment by mon5termatt** [comment]
[Benchy400.zip](https://github.com/user-attachments/files/16492886/Benchy400.zip)

**Comment by mon5termatt** [comment]
![image](https://github.com/user-attachments/assets/7b956d81-9eb6-45a4-b66b-bcb6718b2c97)

**Comment by PoohWoah** [comment]
> 我无法提供相同的文件，因为它具有版权，并且我无法共享它，但是我将使用我的设置提供一个长凳。

It's okay, thank you.

**Comment by BTTJUSTIN** [comment]
This bug was fixed in FW version V1.0.1
